### ISSUE TITLE
Can't install on macOS 13.1 and mamba

### ISSUE THREAD

**Issue by StFroese** [uvemas/ViTables#115]
**Describe your problem**

Tried to install the ViTables using pip in mamba environment with mamba 1.0.0 and conda 4.14.0

`pip install ViTables`

I get the following traceback
```zsh
(cta-dev-origin) ~/D/p/a/a/day17 ❯❯❯ pip install ViTables                                                                                    main ✱ ◼
Collecting ViTables
  Using cached ViTables-3.0.2-py3-none-any.whl (1.0 MB)
Requirement already satisfied: numexpr>=2.0 in /Users/stefan/mambaforge/envs/cta-dev-origin/lib/python3.9/site-packages (from ViTables) (2.8.3)
Requirement already satisfied: tables>=3.0 in /Users/stefan/mambaforge/envs/cta-dev-origin/lib/python3.9/site-packages (from ViTables) (3.7.0)
Collecting PyQt5>=5.5.1
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/stefan/mambaforge/envs/cta-dev-origin/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/stefan/mambaforge/envs/cta-dev-origin/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/stefan/mambaforge/envs/cta-dev-origin/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/stefan/mambaforge/envs/cta-dev-origin/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/01/xdkyf7rj09v44h1vrvk2q29c0000gn/T/pip-build-env-s8dx5q3k/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/01/xdkyf7rj09v44h1vrvk2q29c0000gn/T/pip-build-env-s8dx5q3k/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/01/xdkyf7rj09v44h1vrvk2q29c0000gn/T/pip-build-env-s8dx5q3k/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/01/xdkyf7rj09v44h1vrvk2q29c0000gn/T/pip-build-env-s8dx5q3k/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/01/xdkyf7rj09v44h1vrvk2q29c0000gn/T/pip-build-env-s8dx5q3k/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/01/xdkyf7rj09v44h1vrvk2q29c0000gn/T/pip-build-env-s8dx5q3k/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Alternative**

I downloaded the binary package and tried `pip install ~/Downloads/ViTables-3.0.2-py3-none-any.whl` which gives me the same error.

**Comment by m3lab-zzl** [comment]
I got the same error on M1 macbook

**Comment by StFroese** [comment]
I'm also on M1

**Comment by m3lab-zzl** [comment]
As there is no osx-arm64 label on [the CONDA page](https://anaconda.org/conda-forge/vitables), I suppose it is not supported yet. 

For example, [this package](https://anaconda.org/conda-forge/arm_pyart) has osx-arm64 label.

**Comment by maxnoe** [comment]
The repository for the conda-forge build is here:
https://github.com/conda-forge/vitables-feedstock

Instructions on how to add osx-arm64 support to a conda-forge package are given here:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by maxnoe** [comment]
Just to note: the issue here is not actually vitables, the instalation of pyqt5 fails

**Comment by StFroese** [comment]
Added osx-arm64 to the conda feedstock, works now for python 3.9
