### ISSUE TITLE
Wrong with numpy 'VisibleDeprecationWarning'

### ISSUE THREAD

**Issue by lkkkkkkl** [uvemas/ViTables#129]
when I tried to use vitables path to open the app, I got 
vitables ./data/train_point_clouds.h5
Traceback (most recent call last):
  File "/home/lkl/miniconda3/bin/vitables", line 5, in <module>
    from vitables.start import gui
  File "/home/lkl/miniconda3/lib/python3.12/site-packages/vitables/start.py", line 31, in <module>
    from vitables.vtapp import VTApp
  File "/home/lkl/miniconda3/lib/python3.12/site-packages/vitables/vtapp.py", line 55, in <module>
    import vitables.csv.import_csv as importcsv
  File "/home/lkl/miniconda3/lib/python3.12/site-packages/vitables/csv/import_csv.py", line 65, in <module>
    import vitables.csv.csvutils as csvutils
  File "/home/lkl/miniconda3/lib/python3.12/site-packages/vitables/csv/csvutils.py", line 39, in <module>
    warnings.filterwarnings("ignore", category=numpy.VisibleDeprecationWarning)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkl/miniconda3/lib/python3.12/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'

**Comment by carlosal1015** [comment]
Same error here https://github.com/uvemas/ViTables/blob/v3.1.0/vitables/vtcsv/csvutils.py#L41

```bash
$ vitables 
Traceback (most recent call last):
  File "/usr/bin/vitables", line 5, in <module>
    from vitables.start import gui
  File "/usr/lib/python3.13/site-packages/vitables/start.py", line 31, in <module>
    from vitables.vtapp import VTApp
  File "/usr/lib/python3.13/site-packages/vitables/vtapp.py", line 55, in <module>
    import vitables.csv.import_csv as importcsv
  File "/usr/lib/python3.13/site-packages/vitables/csv/import_csv.py", line 65, in <module>
    import vitables.csv.csvutils as csvutils
  File "/usr/lib/python3.13/site-packages/vitables/csv/csvutils.py", line 39, in <module>
    warnings.filterwarnings("ignore", category=numpy.VisibleDeprecationWarning)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
                         "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'
```

Related https://github.com/pandas-dev/pandas/issues/54505

**Comment by carlosal1015** [comment]
Already fixed, but not a new release yet.

https://github.com/uvemas/ViTables/pull/127
