### ISSUE TITLE
Compatibility with new PyQt version?

### ISSUE THREAD

**Issue by marfel** [uvemas/ViTables#50]
Hi,

I recently updated my Ubuntu 16.04 system to include the newest PyQt package (for QGIS), and now vitables fails to start:

```
Traceback (most recent call last):
  File "/usr/bin/vitables", line 105, in <module>
    main(sys.argv)
  File "/usr/bin/vitables", line 48, in main
    from vitables.vtapp import VTApp
  File "/usr/share/vitables/vitables/vtapp.py", line 41, in <module>
    import vitables.utils
  File "/usr/share/vitables/vitables/utils.py", line 39, in <module>
    import vitables.vtWidgets.renameDlg as renameDlg
  File "/usr/share/vitables/vitables/vtWidgets/renameDlg.py", line 62, in <module>
    loadUiType(os.path.join(os.path.dirname(__file__),'rename_dlg.ui'))[0]
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 208, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/compiler.py", line 55, in __init__
    CompilerCreatorPolicy())
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 170, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 94, in __init__
    modinfo = plugin_locals["moduleInformation"]()
  File "<string>", line 52, in moduleInformation
  File "/usr/lib/python2.7/dist-packages/qgis/__init__.py", line 26, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python2.7/dist-packages/qgis/PyQt/QtCore.py", line 28, in <module>
    sip.setapi(api, 2)
ValueError: API 'QDate' has already been set to version 1

```

I found a very old reference to this Qt API issue here:
http://osdir.com/ml/python-ipython-user/2012-02/msg00095.html

But the suggested solutions don't help. I'm not a Qt guy so I don't know how to fix this. Anyone help?
Thanks, 
Martin

**Comment by ankostis** [comment]
You may try @alexey-naydenov qt5 branch (I've ben working on it lately):

    pip install git+https://github.com/ankostis/ViTables@qt5

And then, lauch it:    

    vitables

**Comment by uvemas** [comment]
The problem should be fixed with the most recent merges so I close the bug.
