### ISSUE TITLE
Develop version won't start

### ISSUE THREAD

**Issue by Kyrish** [uvemas/ViTables#56]
Immediately after start, I had following issue:
alex@cylon:~$ vitables

Traceback (most recent call last):
  File "/usr/local/bin/vitables", line 7, in <module>
    from vitables.start import gui
  File "/usr/local/lib/python2.7/dist-packages/vitables/start.py", line 37, in <module>
    from vitables.vtapp import VTApp
  File "/usr/local/lib/python2.7/dist-packages/vitables/vtapp.py", line 37, in <module>
    import vitables.utils
  File "/usr/local/lib/python2.7/dist-packages/vitables/utils.py", line 40, in <module>
    import vitables.vtwidgets.renamedlg as renamedlg
  File "/usr/local/lib/python2.7/dist-packages/vitables/vtwidgets/renamedlg.py", line 62, in <module>
    loadUiType(os.path.join(os.path.dirname(__file__),'rename_dlg.ui'))[0]
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 210, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Compiler/compiler.py", line 139, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 984, in parse
    document = parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/vitables/vtwidgets/rename_dlg.ui'

Seems like *.ui files are not copied during python setup.py install

**Comment by ankostis** [comment]
I tested generated wheel from `2.2.1.dev0` (master@a7dc69420e) and it now works.

**Comment by heroxbd** [comment]
Let's close this issue.

**Comment by Kyrish** [comment]
The problem is still there. I'm on MacOs 10.12.6. Python 2.7 and Qt stuff are installed via Homebrew. 
I'm doing: python setup.py install, so far so good. But when I try to run I get following:

alex$ vitables
Traceback (most recent call last):
  File "/usr/local/bin/vitables", line 11, in <module>
    load_entry_point('ViTables==2.2a1', 'gui_scripts', 'vitables')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/ViTables-2.2a1-py2.7.egg/vitables/start.py", line 37, in <module>
    from vitables.vtapp import VTApp
  File "/usr/local/lib/python2.7/site-packages/ViTables-2.2a1-py2.7.egg/vitables/vtapp.py", line 37, in <module>
    import vitables.utils
  File "/usr/local/lib/python2.7/site-packages/ViTables-2.2a1-py2.7.egg/vitables/utils.py", line 40, in <module>
    import vitables.vtwidgets.renamedlg as renamedlg
  File "/usr/local/lib/python2.7/site-packages/ViTables-2.2a1-py2.7.egg/vitables/vtwidgets/renamedlg.py", line 62, in <module>
    loadUiType(os.path.join(os.path.dirname(__file__),'rename_dlg.ui'))[0]
  File "/usr/local/lib/qt-4/python2.7/site-packages/PyQt4/uic/__init__.py", line 208, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "/usr/local/lib/qt-4/python2.7/site-packages/PyQt4/uic/Compiler/compiler.py", line 140, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/local/lib/qt-4/python2.7/site-packages/PyQt4/uic/uiparser.py", line 974, in parse
    document = parse(filename)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/ViTables-2.2a1-py2.7.egg/vitables/vtwidgets/rename_dlg.ui'
