### ISSUE TITLE
Error on MAC High Sierra + miniconda 3

### ISSUE THREAD

**Issue by Civilduino** [uvemas/ViTables#91]
Hi,

I have macOS High Sierra 10.13.5 and installed miniconda 3, followed by different packages as numpy, matplotlib, spyder and vitables. I first tried installing vitables directly from conda-forge but got a strange error. Then I tried cloning directly the GitHub and using the setup.py and it I got the same error again when trying to run vitables (see below):

yannie$ vitables
/Users/yannie/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/Users/yannie/miniconda3/bin/vitables", line 11, in <module>
    load_entry_point('ViTables==3.0.0', 'gui_scripts', 'vitables')()
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/ViTables-3.0.0-py3.6.egg/vitables/start.py", line 33, in <module>
    from vitables.vtapp import VTApp
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/ViTables-3.0.0-py3.6.egg/vitables/vtapp.py", line 36, in <module>
    import vitables.utils
  File "/Users/yannie/miniconda3/lib/python3.6/site-packages/ViTables-3.0.0-py3.6.egg/vitables/utils.py", line 48, in <module>
    DEFAULT_ENCODING = locale.getdefaultlocale()[1]
  File "/Users/yannie/miniconda3/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/yannie/miniconda3/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

I did remove the requirement for the PyQt5 in the install_requires and nothing. I really do not understand this error.

Thanks!

**Comment by uvemas** [comment]
Hi,

I have never seen this error before. Googling a little bit I've found these links:

https://github.com/ContinuumIO/anaconda-issues/issues/6678

https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility#40846742

Hope it helps.
